### ISSUE TITLE
How is this better than plain pip freeze?

### ISSUE THREAD

**Issue by msabramo** [marksteve/pip-pin#1]
I'm sure that I'm missing something, but maybe whatever that is should be added to the docs so that others don't miss it too. 

Why is this better than a regular pip freeze?

**Comment by marksteve** [comment]
@msabramo It doesn't replace pip freeze but rather augments it. `pip freeze` lists all installed packages in your environment including their dependencies. But you only usually want the packages you directly depend on in your `requirements.txt`. pin-pin allows you to pin the currently installed version of your packages in your `requirements.txt` using the output of `pip freeze`.

**Comment by rstacruz** [comment]
Another way to look IMHO is that this lets you start small projects without making a new `virtualenv`.

**Comment by msabramo** [comment]
> But you only usually want the packages you directly depend on in your requirements.txt

Are we talking about an application or a library?

For a **library**, I agree that you want to pin the least amount possible, though I would usually just put those requirements as `install_requires` in `setup.py` and not even use a `requirements.txt` file (or maybe have one but just for setting up a dev environment).

For an **application**, I like to pin everything in the virtualenv, because you want the environment to be fully reproducible and a change in any package could potentially break something. So here I'd probably use `pip freeze`.

My thinking on this was largely shaped by this blog post: https://caremad.io/blog/setup-vs-requirement/

What are you using `pip-pin` for? I'm wondering if there is another use case that I haven't thought of.

By the way, another tool you might be interested in looking at is [pundler](https://github.com/steder/pundler). That one also assists in pinning packages. As the name suggests, it is inspired by [Bundler](http://bundler.io/) from the Ruby world.

**Comment by marksteve** [comment]
For applications. I prefer not having them, the dependencies of my dependencies, in my `requirements.txt` to keep it clean and easier to read. I sort of *trust* packages I depend on to settle their dependencies properly.

Though upon reading the blog post you linked and discovering the `-r` argument of `pip freeze`, I think I'll start pinning my sub-dependencies too now. pundler looks interesting!

I'll be closing this issue with the conclusion that this utility wasn't such a good idea :P But I learned some about package management! :+1: 

Thanks @msabramo :)

**Comment by msabramo** [comment]
No problem, @marksteve, glad that it was interesting for you! :+1:
